/*
 * Dog - WebSocket Connector
 * 
 * Copyright (c) 2013-2014 Teodoro Montanaro and Luigi De Russis
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
package it.polito.elite.dog.communication.websocket.message;

/**
 * The JSON Response message
 * 
 * @author <a href="mailto:teo.montanaro@gmail.com">Teodoro Montanaro</a>
 * @author <a href="mailto:luigi.derussis@polito.it">Luigi De Russis</a>
 * @see <a href="http://elite.polito.it">http://elite.polito.it</a>
 * 
 */
public class Response extends BaseJsonData
{
	
	// sequence number used to indicate the request for which we are sending the
	// response (generated by the client)
	private String sequenceNumber;
	// action to perform (possible values: GET, PUT, POST, DELETE)
	private String action;
	// path used to find the right method that has to be invoked
	private String endPoint;
	// single parameter or list of parameters to pass to the method (they are in
	// json format)
	private String parameters;
	// response obtained by methods
	private Object response;
	
	/**
	 * @return the sequenceNumber
	 */
	public String getSequenceNumber()
	{
		return sequenceNumber;
	}
	
	/**
	 * @param sequenceNumber
	 *            the sequenceNumber to set
	 */
	public void setSequenceNumber(String sequenceNumber)
	{
		this.sequenceNumber = sequenceNumber;
	}
	
	/**
	 * @return the action
	 */
	public String getAction()
	{
		return action;
	}
	
	/**
	 * @param action
	 *            the action to set
	 */
	public void setAction(String action)
	{
		this.action = action;
	}
	
	/**
	 * @return the endPoint
	 */
	public String getEndPoint()
	{
		return endPoint;
	}
	
	/**
	 * @param endPoint
	 *            the endPoint to set
	 */
	public void setEndPoint(String endPoint)
	{
		this.endPoint = endPoint;
	}
	
	/**
	 * @return the parameters
	 */
	public String getParameters()
	{
		return parameters;
	}
	
	/**
	 * @param parameters
	 *            the parameters to set
	 */
	public void setParameters(String parameters)
	{
		this.parameters = parameters;
	}
	
	/**
	 * @return the response
	 */
	public Object getResponse()
	{
		return response;
	}
	
	/**
	 * @param response
	 *            the response to set
	 */
	public void setResponse(Object response)
	{
		this.response = response;
	}
	
}