/*
 * Dog - WebSocket Endpoint
 * 
 * Copyright (c) 2013-2014 Teodoro Montanaro
 * contact: teo.montanaro@gmail.com
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
package it.polito.elite.dog.communication.websocket.message;

public class WebSocketJsonResponse extends WebSocketJsonData
{
	
	// sequence number used to indicate the request for which we are sending the
	// response (generated by the client)
	private String sequenceNumber;
	// action to perform (possible values: GET, PUT, POST, DELETE)
	private String action;
	// path used to find the right method that has to be invoked
	private String endPoint;
	// single parameter or list of parameters to pass to the method (they are in
	// json format)
	private String parameters;
	// response obtained by methods
	private Object response;
	
	// get sequenceNumber
	public String getSequenceNumber()
	{
		return sequenceNumber;
	}
	
	// setter for sequenceNumber
	public void setSequenceNumber(String sequenceNumber)
	{
		this.sequenceNumber = sequenceNumber;
	}
	
	// get action
	public String getAction()
	{
		return action;
	}
	
	// setter for action
	public void setAction(String action)
	{
		this.action = action;
	}
	
	// get endPoint
	public String getEndPoint()
	{
		return endPoint;
	}
	
	// setter for endPoint
	public void setEndPoint(String endPoint)
	{
		this.endPoint = endPoint;
	}
	
	// get parameters
	public String getParameters()
	{
		return parameters;
	}
	
	// setter for parameters
	public void setParameters(String parameters)
	{
		this.parameters = parameters;
	}
	
	// get response
	public Object getResponse()
	{
		return response;
	}
	
	// setter for response
	public void setResponse(Object response)
	{
		this.response = response;
	}
	
}