package it.polito.elite.dog.communication.ws.message;

public class WebsocketJsonRequest extends WebsocketJsonData
{
	// sequence number used to indicate the request for which we are sending the
	// response (generated by the client)
	private String sequenceNumber;
	// action to perform (possible values: GET, PUT, POST, DELETE)
	private String action;
	// path used to find the right method that has to be invoked
	private String endPoint;
	// single parameter or list of parameters to pass to the method (they are in
	// json format)
	private String parameters;
	
	// get sequenceNumber
	public String getSequenceNumber()
	{
		return sequenceNumber;
	}
	
	// setter for sequenceNumber
	public void setSequenceNumber(String sequenceNumber)
	{
		this.sequenceNumber = sequenceNumber;
	}
	
	// get action
	public String getAction()
	{
		return action;
	}
	
	// setter for action
	public void setAction(String action)
	{
		this.action = action;
	}
	
	// get endPoint
	public String getEndPoint()
	{
		return endPoint;
	}
	
	// setter for endPoint
	public void setEndPoint(String endPoint)
	{
		this.endPoint = endPoint;
	}
	
	// get parameters
	public String getParameters()
	{
		return parameters;
	}
	
	// setter for parameters
	public void setParameters(String parameters)
	{
		this.parameters = parameters;
	}
	
}